#!/usr/bin/env bash
set -eo pipefail

function main {

  # Check if the release file exists
  if ! [ -s 'new_releases.tmp' ]; then
    echo "=> No file new_releases.tmp to use for the commit"
    exit 0
  fi

  git checkout --track origin/master

  # Take https format and convert it to a SSH one so we can push from the CI
  local APP_GIT_CI="$(echo "$CI_REPOSITORY_URL" | perl -pe 's#.*@(.+?(\:\d+)?)/#git@\1:#')";

  # Gitlab default URL is https and the push doesn't work
  git remote set-url origin "$APP_GIT_CI"

  echo "=> set new origin $APP_GIT_CI";

  # Force add hidden files from gitignore + updated README.md
  git add -f README.md;

  git status;

  git commit -m "[release] $(cat ./new_releases.tmp)"
  git push origin master;
}

main
