{
 "title": "Android / Checkout",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "increase_interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "sf_availability",
    "query": "($S + !($S || $F)) / (($S + $F) + !($S || $F)) * 100"
   }
  ]
 },
 "panels": [
  {
   "title": "Screen views/$increase_interval",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(screen_id) (increase(client_android_core_checkout_screenView_total[$increase_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Dynamic Plan/Subscription", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Get Dynamic Plans - availability/$increase_interval",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "targets": [
    { "expression": "$sf_availability", "type": "math" }
   ]
  },
  {
   "title": "Get Dynamic Plans - successes/$increase_interval",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "targets": [
    {
     "expr": "sum by(status) (increase(client_android_core_checkout_dynamicPlans_getDynamicPlans_total{status=\"http2xx\"}[$increase_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Get Dynamic Plans - failures/$increase_interval",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "targets": [
    {
     "expr": "sum by(status) (increase(client_android_core_checkout_dynamicPlans_getDynamicPlans_total{status!=\"http2xx\"}[$increase_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Get Dynamic Subscription - availability/$increase_interval",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
   "targets": [
    { "expression": "$sf_availability", "type": "math" }
   ]
  },
  {
   "title": "Get Dynamic Subscription - successes/$increase_interval",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 17 },
   "targets": [
    {
     "expr": "sum by(status) (increase(client_android_core_checkout_dynamicPlans_getDynamicSubscription_total{status=\"http2xx\"}[$increase_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Get Dynamic Subscription - failures/$increase_interval",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 17 },
   "targets": [
    {
     "expr": "sum by(status) (increase(client_android_core_checkout_dynamicPlans_getDynamicSubscription_total{status!=\"http2xx\"}[$increase_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Billing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Subscribe (google) - availability/$increase_interval",
   "type": "timeseries",
   "description": "Creating or updating a subscription managed by Google (`payments/v4/subscription`).",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 26 },
   "targets": [
    { "expression": "$sf_availability", "type": "math" }
   ]
  },
  {
   "title": "Subscribe (google) - successes/$increase_interval",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 26 },
   "targets": [
    {
     "expr": "sum by(status) (increase(client_android_core_checkout_billing_subscribe_total{status=\"http2xx\", manager=\"google\"}[$increase_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Subscribe (google) - failures/$increase_interval",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 26 },
   "targets": [
    {
     "expr": "sum by(status) (increase(client_android_core_checkout_billing_subscribe_total{status!=\"http2xx\", manager=\"google\"}[$increase_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Subscribe (proton) - availability/$increase_interval",
   "type": "timeseries",
   "description": "Creating or updating a subscription managed by Proton (`payments/v4/subscription`).",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 34 },
   "targets": [
    { "expression": "$sf_availability", "type": "math" }
   ]
  },
  {
   "title": "Subscribe (proton) - successes/$increase_interval",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 34 },
   "targets": [
    {
     "expr": "sum by(status) (increase(client_android_core_checkout_billing_subscribe_total{status=\"http2xx\", manager=\"proton\"}[$increase_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Subscribe (proton) - failures/$increase_interval",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 34 },
   "targets": [
    {
     "expr": "sum by(status) (increase(client_android_core_checkout_billing_subscribe_total{status!=\"http2xx\", manager=\"proton\"}[$increase_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Card billing",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "collapsed": true,
   "panels": [
    {
     "title": "Validate plan - availability/$increase_interval",
     "type": "timeseries",
     "description": "Validate a plan before subscribing (`payments/v4/subscription/check`).",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 26 },
     "targets": [
      { "expression": "$sf_availability", "type": "math" }
     ]
    },
    {
     "title": "Validate plan - successes/$increase_interval",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 26 },
     "targets": [
      {
       "expr": "sum by(status) (increase(client_android_core_checkout_cardBilling_validatePlan_total{status=\"http2xx\"}[$increase_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Validate plan - failures/$increase_interval",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 26 },
     "targets": [
      {
       "expr": "sum by(status) (increase(client_android_core_checkout_cardBilling_validatePlan_total{status!=\"http2xx\"}[$increase_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Create payment token - availability/$increase_interval",
     "type": "timeseries",
     "description": "Creating a payment token when paying with a credit card.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 34 },
     "targets": [
      { "expression": "$sf_availability", "type": "math" }
     ]
    },
    {
     "title": "Create payment token - successes/$increase_interval",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 34 },
     "targets": [
      {
       "expr": "sum by(status) (increase(client_android_core_checkout_cardBilling_createPaymentToken_total{status=\"http2xx\"}[$increase_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Create payment token - failures/$increase_interval",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 34 },
     "targets": [
      {
       "expr": "sum by(status) (increase(client_android_core_checkout_cardBilling_createPaymentToken_total{status!=\"http2xx\"}[$increase_interval]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  { "title": "Google In App Purchase", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Product query - availability/$increase_interval",
   "type": "timeseries",
   "description": "Querying for products via Google Billing library.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 44 },
   "targets": [
    { "expression": "$sf_availability", "type": "math" }
   ]
  },
  {
   "title": "Product query - successes/$increase_interval",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 44 },
   "targets": [
    {
     "expr": "sum by(status) (increase(client_android_core_checkout_giapBilling_productQuery_total{status=\"success\"}[$increase_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Product query - failures/$increase_interval",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 44 },
   "targets": [
    {
     "expr": "sum by(status) (increase(client_android_core_checkout_giapBilling_productQuery_total{status!=\"success\"}[$increase_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Query subscriptions - availability/$increase_interval",
   "type": "timeseries",
   "description": "Querying for subscriptions via Google Billing library to check if there are no unredeemed purchases.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 52 },
   "targets": [
    { "expression": "$sf_availability", "type": "math" }
   ]
  },
  {
   "title": "Query subscriptions - successes/$increase_interval",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(status) (increase(client_android_core_checkout_giapBilling_querySubscriptions_total{status=\"success\"}[$increase_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Query subscriptions - failures/$increase_interval",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 52 },
   "targets": [
    {
     "expr": "sum by(status) (increase(client_android_core_checkout_giapBilling_querySubscriptions_total{status!=\"success\"}[$increase_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unredeemed purchases/$increase_interval",
   "type": "timeseries",
   "description": "An unredeemed/unacknowledged Google purchase has been detected.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(client_android_core_checkout_giapBilling_unredeemed_total[$increase_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Launch billing - availability/$increase_interval",
   "type": "timeseries",
   "description": "Launching the Google Billing flow.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expression": "$sf_availability", "type": "math" }
   ]
  },
  {
   "title": "Launch billing - successes/$increase_interval",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(status) (increase(client_android_core_checkout_giapBilling_launchBilling_total{status=\"success\"}[$increase_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Launch billing - failures/$increase_interval",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 66 },
   "targets": [
    {
     "expr": "sum by(status) (increase(client_android_core_checkout_giapBilling_launchBilling_total{status!=\"success\"}[$increase_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Purchase - availability/$increase_interval",
   "type": "timeseries",
   "description": "The purchase result coming from the Google Billing flow.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 74 },
   "targets": [
    { "expression": "$sf_availability", "type": "math" }
   ]
  },
  {
   "title": "Purchase - successes/$increase_interval",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(status) (increase(client_android_core_checkout_giapBilling_purchase_total{status=\"success\"}[$increase_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Purchase - failures/$increase_interval",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 74 },
   "targets": [
    {
     "expr": "sum by(status) (increase(client_android_core_checkout_giapBilling_purchase_total{status!=\"success\"}[$increase_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Validate plan - availability/$increase_interval",
   "type": "timeseries",
   "description": "Validate a plan before subscribing (`payments/v4/subscription/check`).",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 82 },
   "targets": [
    { "expression": "$sf_availability", "type": "math" }
   ]
  },
  {
   "title": "Validate plan - successes/$increase_interval",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 82 },
   "targets": [
    {
     "expr": "sum by(status) (increase(client_android_core_checkout_giapBilling_validatePlan_total{status=\"http2xx\"}[$increase_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Validate plan - failures/$increase_interval",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 82 },
   "targets": [
    {
     "expr": "sum by(status) (increase(client_android_core_checkout_giapBilling_validatePlan_total{status!=\"http2xx\"}[$increase_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Create payment token - availability/$increase_interval",
   "type": "timeseries",
   "description": "Creating a payment token when paying with Google.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 90 },
   "targets": [
    { "expression": "$sf_availability", "type": "math" }
   ]
  },
  {
   "title": "Create payment token - successes/$increase_interval",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 90 },
   "targets": [
    {
     "expr": "sum by(status) (increase(client_android_core_checkout_giapBilling_createPaymentToken_total{status=\"http2xx\"}[$increase_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Create payment token - failures/$increase_interval",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 90 },
   "targets": [
    {
     "expr": "sum by(status) (increase(client_android_core_checkout_giapBilling_createPaymentToken_total{status!=\"http2xx\"}[$increase_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Acknowledge - availability/$increase_interval",
   "type": "timeseries",
   "description": "A purchase is acknowledged to Google.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 98 },
   "targets": [
    { "expression": "$sf_availability", "type": "math" }
   ]
  },
  {
   "title": "Acknowledge - successes/$increase_interval",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(status) (increase(client_android_core_checkout_giapBilling_acknowledge_total{status=\"success\"}[$increase_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Acknowledge - failures/$increase_interval",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 98 },
   "targets": [
    {
     "expr": "sum by(status) (increase(client_android_core_checkout_giapBilling_acknowledge_total{status!=\"success\"}[$increase_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Existing payment methods",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 106 },
   "collapsed": true,
   "panels": [
    {
     "title": "Get payment methods - availability/$increase_interval",
     "type": "timeseries",
     "description": "Fetching already saved payment methods (`payments/v4/methods`).",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 90 },
     "targets": [
      { "expression": "$sf_availability", "type": "math" }
     ]
    },
    {
     "title": "Get payment methods - successes/$increase_interval",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 90 },
     "targets": [
      {
       "expr": "sum by(status) (increase(client_android_core_checkout_paymentMethods_getPaymentMethods_total{status=\"http2xx\"}[$increase_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Get payment methods - failures/$increase_interval",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 90 },
     "targets": [
      {
       "expr": "sum by(status) (increase(client_android_core_checkout_paymentMethods_getPaymentMethods_total{status!=\"http2xx\"}[$increase_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Validate plan - availability/$increase_interval",
     "type": "timeseries",
     "description": "Validate a plan before subscribing (`payments/v4/subscription/check`).",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 98 },
     "targets": [
      {
       "expr": "sum(increase(client_android_core_checkout_paymentMethods_validatePlan_total{status=\"http2xx\"}[$increase_interval]))",
       "legendFormat": "Successes"
      },
      {
       "expr": "sum(increase(client_android_core_checkout_paymentMethods_validatePlan_total{status!=\"http2xx\"}[$increase_interval]))",
       "legendFormat": "Failures"
      },
      { "expression": "$sf_availability", "type": "math" }
     ]
    },
    {
     "title": "Validate plan - successes/$increase_interval",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 98 },
     "targets": [
      {
       "expr": "sum by(status) (increase(client_android_core_checkout_paymentMethods_validatePlan_total{status=\"http2xx\"}[$increase_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Validate plan - failures/$increase_interval",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 98 },
     "targets": [
      {
       "expr": "sum by(status) (increase(client_android_core_checkout_paymentMethods_validatePlan_total{status!=\"http2xx\"}[$increase_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Create payment token - availability/$increase_interval",
     "type": "timeseries",
     "description": "Creating a payment token when paying with an existing payment method.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 106 },
     "targets": [
      {
       "expr": "sum(increase(client_android_core_checkout_paymentMethods_createPaymentToken_total{status=\"http2xx\"}[$increase_interval]))",
       "legendFormat": "Successes"
      },
      {
       "expr": "sum(increase(client_android_core_checkout_paymentMethods_createPaymentToken_total{status!=\"http2xx\"}[$increase_interval]))",
       "legendFormat": "Failures"
      },
      { "expression": "$sf_availability", "type": "math" }
     ]
    },
    {
     "title": "Create payment token - successes/$increase_interval",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 106 },
     "targets": [
      {
       "expr": "sum by(status) (increase(client_android_core_checkout_paymentMethods_createPaymentToken_total{status=\"http2xx\"}[$increase_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Create payment token - failures/$increase_interval",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 106 },
     "targets": [
      {
       "expr": "sum by(status) (increase(client_android_core_checkout_paymentMethods_createPaymentToken_total{status!=\"http2xx\"}[$increase_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Subscribe - availability/$increase_interval",
     "type": "timeseries",
     "description": "Creating or updating a subscription using an existing payment method (`payments/v4/subscription`).",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 114 },
     "targets": [
      {
       "expr": "sum(increase(client_android_core_checkout_paymentMethods_subscribe_total{status=\"http2xx\"}[$increase_interval]))",
       "legendFormat": "Successes"
      },
      {
       "expr": "sum(increase(client_android_core_checkout_paymentMethods_subscribe_total{status!=\"http2xx\"}[$increase_interval]))",
       "legendFormat": "Failures"
      },
      { "expression": "$sf_availability", "type": "math" }
     ]
    },
    {
     "title": "Subscribe - successes/$increase_interval",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 114 },
     "targets": [
      {
       "expr": "sum by(status) (increase(client_android_core_checkout_paymentMethods_subscribe_total{status=\"http2xx\"}[$increase_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Subscribe - failures/$increase_interval",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 114 },
     "targets": [
      {
       "expr": "sum by(status) (increase(client_android_core_checkout_paymentMethods_subscribe_total{status!=\"http2xx\"}[$increase_interval]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}