{
 "title": "Android / Sign-up",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "increase_interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "sf_availability",
    "query": "($S + !($S || $F)) / (($S + $F) + !($S || $F)) * 100"
   }
  ]
 },
 "panels": [
  {
   "title": "Sign-up Android Availability",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expression": "$A / ($A + $B) * 100", "type": "math" },
    { "expression": "$D / ($D + $E) * 100", "type": "math" },
    { "expression": "$G / ($G + $H) * 100", "type": "math" }
   ]
  },
  {
   "title": "Screen views/$increase_interval",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "sum by(screen_id) (increase(client_android_core_signup_screenView_total[$increase_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Screen: Choose username/email", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Fetch domains - availability/$increase_interval",
   "type": "timeseries",
   "description": "Excludes `notConnected` status.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 14 },
   "targets": [
    { "expression": "$sf_availability", "type": "math" }
   ]
  },
  {
   "title": "Fetch domains - successes/$increase_interval",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 14 },
   "targets": [
    {
     "expr": "sum by(status) (increase(client_android_core_signup_fetchDomains_total{status=\"http2xx\"}[$increase_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Fetch domains - failures/$increase_interval",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 14 },
   "targets": [
    {
     "expr": "sum by(status) (increase(client_android_core_signup_fetchDomains_total{status!=\"http2xx\"}[$increase_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Is username available - availability/$increase_interval",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 22 },
   "targets": [
    { "expression": "$sf_availability", "type": "math" }
   ]
  },
  {
   "title": "Is username available - successes/$increase_interval",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 22 },
   "targets": [
    {
     "expr": "sum by(status) (increase(client_android_core_signup_usernameAvailability_total{status=\"http2xx\"}[$increase_interval]))",
     "legendFormat": "username {{status}}"
    }
   ]
  },
  {
   "title": "Is username available - failures/$increase_interval",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 22 },
   "targets": [
    {
     "expr": "sum by(status) (increase(client_android_core_signup_usernameAvailability_total{status!=\"http2xx\"}[$increase_interval]))",
     "legendFormat": "username {{status}}"
    }
   ]
  },
  {
   "title": "Is email available - successes/$increase_interval",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 30 },
   "targets": [
    {
     "expr": "sum by(status) (increase(client_android_core_signup_emailAvailability_total{status=\"http2xx\"}[$increase_interval]))",
     "legendFormat": "email {{status}}"
    }
   ]
  },
  {
   "title": "Is email available - failures/$increase_interval",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 30 },
   "targets": [
    {
     "expr": "sum by(status) (increase(client_android_core_signup_emailAvailability_total{status!=\"http2xx\"}[$increase_interval]))",
     "legendFormat": "email {{status}}"
    }
   ]
  },
  { "title": "Screen: Creating an account", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Account creation - total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "sum (increase(client_android_core_signup_accountCreation_total{}[$increase_interval]))",
     "legendFormat": "Account creation total"
    }
   ]
  },
  {
   "title": "Account creation - availability/$increase_interval",
   "type": "timeseries",
   "description": "Excluding http409UsernameConflict and http422HvRequired.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 47 },
   "targets": [
    { "expression": "$sf_availability", "type": "math" }
   ]
  },
  {
   "title": "Account creation - successes/$increase_interval",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 47 },
   "targets": [
    {
     "expr": "sum by(status) (increase(client_android_core_signup_accountCreation_total{status=\"http2xx\"}[$increase_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Account creation - failures/$increase_interval",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 47 },
   "targets": [
    {
     "expr": "sum by(status) (increase(client_android_core_signup_accountCreation_total{status!=\"http2xx\"}[$increase_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Login after signup - total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 55 },
   "targets": [
    {
     "expr": "sum (increase(client_android_core_signup_login_total{}[$increase_interval]))",
     "legendFormat": "Login after signup total"
    }
   ]
  },
  {
   "title": "Login after signup - availability/$increase_interval",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 63 },
   "targets": [
    { "expression": "$sf_availability", "type": "math" }
   ]
  },
  {
   "title": "Login after signup - successes/$increase_interval",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 63 },
   "targets": [
    {
     "expr": "sum by(status) (increase(client_android_core_signup_login_total{status=\"http2xx\"}[$increase_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Login after signup - failures/$increase_interval",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 63 },
   "targets": [
    {
     "expr": "sum by(status) (increase(client_android_core_signup_login_total{status!=\"http2xx\"}[$increase_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unlock user - successes/$increase_interval",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 71 },
   "targets": [
    {
     "expr": "sum by(status) (increase(client_android_core_signup_unlockUser_total{status=\"success\"}[$increase_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unlock user - failures/$increase_interval",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 71 },
   "targets": [
    {
     "expr": "sum by(status) (increase(client_android_core_signup_unlockUser_total{status!=\"success\"}[$increase_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "User check - successes/$increase_interval",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 71 },
   "targets": [
    {
     "expr": "sum by(status) (increase(client_android_core_signup_userCheck_total{status=\"success\"}[$increase_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "User check - failures/$increase_interval",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 71 },
   "targets": [
    {
     "expr": "sum by(status) (increase(client_android_core_signup_userCheck_total{status!=\"success\"}[$increase_interval]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}