{
 "title": "Android / Recovery",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "increase_interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Screen views/$increase_interval",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(screen_id) (increase(client_android_core_accountRecovery_screenView_total[$increase_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cancellation availability/$increase_interval",
   "type": "timeseries",
   "description": "Excludes `notConnected` status.",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 9 },
   "targets": [
    { "expression": "$A / ($A + $B) * 100", "type": "math" }
   ]
  },
  {
   "title": "Cancellation success/$increase_interval",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 9 },
   "targets": [
    {
     "expr": "sum by(status) (increase(client_android_core_accountRecovery_cancellation_total{status=\"http2xx\"}[$increase_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cancellation failures/$increase_interval",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 9 },
   "targets": [
    {
     "expr": "sum by(status) (increase(client_android_core_accountRecovery_cancellation_total{status!=\"http2xx\"}[$increase_interval]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}