{
 "title": "Android / Sign up",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "increase_interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Screen views/$increase_interval",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(screen_id) (increase(client_android_core_signup_screenView_total[$increase_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Screen: Choose username/email", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Fetch domains - availability/$increase_interval",
   "type": "timeseries",
   "description": "Excludes `notConnected` status.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "targets": [
    { "expression": "$A / ($A + $B) * 100", "type": "math" }
   ]
  },
  {
   "title": "Fetch domains - successes/$increase_interval",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "targets": [
    {
     "expr": "sum by(status) (increase(client_android_core_signup_fetchDomains_total{status=\"http2xx\"}[$increase_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Fetch domains - failures/$increase_interval",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "targets": [
    {
     "expr": "sum by(status) (increase(client_android_core_signup_fetchDomains_total{status!=\"http2xx\"}[$increase_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Is username/email available - successes/$increase_interval",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 17 },
   "targets": [
    {
     "expr": "sum by(status) (increase(client_android_core_signup_usernameAvailability_total{status=\"http2xx\"}[$increase_interval]))",
     "legendFormat": "username {{status}}"
    },
    {
     "expr": "sum by(status) (increase(client_android_core_signup_emailAvailability_total{status=\"http2xx\"}[$increase_interval]))",
     "legendFormat": "email {{status}}"
    }
   ]
  },
  {
   "title": "Is username/email available - failures/$increase_interval",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 17 },
   "targets": [
    {
     "expr": "sum by(status) (increase(client_android_core_signup_usernameAvailability_total{status!=\"http2xx\"}[$increase_interval]))",
     "legendFormat": "username {{status}}"
    },
    {
     "expr": "sum by(status) (increase(client_android_core_signup_emailAvailability_total{status!=\"http2xx\"}[$increase_interval]))",
     "legendFormat": "email {{status}}"
    }
   ]
  },
  { "title": "Screen: Creating an account", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Account creation - availability/$increase_interval",
   "type": "timeseries",
   "description": "Excluding http409UsernameConflict and http422HvRequired.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 26 },
   "targets": [
    { "expression": "$A / ($A + $B) * 100", "type": "math" }
   ]
  },
  {
   "title": "Account creation - successes/$increase_interval",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 26 },
   "targets": [
    {
     "expr": "sum by(status) (increase(client_android_core_signup_accountCreation_total{status=\"http2xx\"}[$increase_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Account creation - failures/$increase_interval",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 26 },
   "targets": [
    {
     "expr": "sum by(status) (increase(client_android_core_signup_accountCreation_total{status!=\"http2xx\"}[$increase_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Login after signup - availability/$increase_interval",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 34 },
   "targets": [
    { "expression": "$A / ($A + $B) * 100", "type": "math" }
   ]
  },
  {
   "title": "Login after signup - successes/$increase_interval",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 34 },
   "targets": [
    {
     "expr": "sum by(status) (increase(client_android_core_signup_login_total{status=\"http2xx\"}[$increase_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Login after signup - failures/$increase_interval",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 34 },
   "targets": [
    {
     "expr": "sum by(status) (increase(client_android_core_signup_login_total{status!=\"http2xx\"}[$increase_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unlock user - successes/$increase_interval",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "sum by(status) (increase(client_android_core_signup_unlockUser_total{status=\"success\"}[$increase_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unlock user - failures/$increase_interval",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 42 },
   "targets": [
    {
     "expr": "sum by(status) (increase(client_android_core_signup_unlockUser_total{status!=\"success\"}[$increase_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "User check - successes/$increase_interval",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 42 },
   "targets": [
    {
     "expr": "sum by(status) (increase(client_android_core_signup_userCheck_total{status=\"success\"}[$increase_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "User check - failures/$increase_interval",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 42 },
   "targets": [
    {
     "expr": "sum by(status) (increase(client_android_core_signup_userCheck_total{status!=\"success\"}[$increase_interval]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}