{
 "title": "Android / Sign in",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "increase_interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Screen views/$increase_interval",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(screen_id) (increase(client_android_core_login_screenView_total[$increase_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "SSO", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Obtain SSO challenge token - availability/$increase_interval",
   "type": "timeseries",
   "description": "Calls to `/auth/info` with SAML intent.\nAvailability excludes `notConnected` and `ssoDomainNotFound` errors.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "targets": [
    { "expression": "$A / ($A + $B) * 100", "type": "math" }
   ]
  },
  {
   "title": "Obtain SSO challenge token - successes/$increase_interval",
   "type": "timeseries",
   "description": "Calls to `/auth/info` with SAML intent.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "targets": [
    {
     "expr": "sum by(status) (increase(client_android_core_login_sso_obtainChallengeToken_total{status=\"http2xx\"}[$increase_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Obtain SSO challenge token - failures/$increase_interval",
   "type": "timeseries",
   "description": "Calls to `/auth/info` with SAML intent.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "targets": [
    {
     "expr": "sum by(status) (increase(client_android_core_login_sso_obtainChallengeToken_total{status!=\"http2xx\"}[$increase_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Identity Provider page load - availability/$increase_interval",
   "type": "timeseries",
   "description": "Loading IdP in a web view.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
   "targets": [
    { "expression": "$A / ($A + $B) * 100", "type": "math" }
   ]
  },
  {
   "title": "Identity Provider page load - successes/$increase_interval",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 17 },
   "targets": [
    {
     "expr": "sum by(status) (increase(client_android_core_login_ssoIdentityProvider_pageLoad_total{status=\"http2xx\"}[$increase_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Identity Provider page load - failures/$increase_interval",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 17 },
   "targets": [
    {
     "expr": "sum by(status) (increase(client_android_core_login_ssoIdentityProvider_pageLoad_total{status!=\"http2xx\"}[$increase_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Identity Provider result - availability/$increase_interval",
   "type": "timeseries",
   "description": "Result from IdP web view.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 25 },
   "targets": [
    { "expression": "$A / ($A + $B) * 100", "type": "math" }
   ]
  },
  {
   "title": "Identity Provider result - successes/$increase_interval",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 25 },
   "targets": [
    {
     "expr": "sum by(status) (increase(client_android_core_login_ssoIdentityProvider_result_total{status=\"success\"}[$increase_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Identity Provider result - failures/$increase_interval",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 25 },
   "targets": [
    {
     "expr": "sum by(status) (increase(client_android_core_login_ssoIdentityProvider_result_total{status!=\"success\"}[$increase_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SSO login - availability/$increase_interval",
   "type": "timeseries",
   "description": "Calls to `/auth` using an SSO token. Availability excludes `notConnected` and `http422` errors.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 33 },
   "targets": [
    { "expression": "$A / ($A + $B) * 100", "type": "math" }
   ]
  },
  {
   "title": "SSO login - successes/$increase_interval",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 33 },
   "targets": [
    {
     "expr": "sum by(status) (increase(client_android_core_login_sso_auth_total{status=\"http2xx\"}[$increase_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SSO login - failures/$increase_interval",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 33 },
   "targets": [
    {
     "expr": "sum by(status) (increase(client_android_core_login_sso_auth_total{status!=\"http2xx\"}[$increase_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Convert an account from External to Internal",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 }
  },
  {
   "title": "Fetch domains - availability/$increase_interval",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 42 },
   "targets": [
    { "expression": "$A / ($A + $B) * 100", "type": "math" }
   ]
  },
  {
   "title": "Fetch domains - successes/$increase_interval",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 42 },
   "targets": [
    {
     "expr": "sum by(status) (increase(client_android_core_login_eaToIafetchDomains_total{status=\"http2xx\"}[$increase_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Fetch domains - failures/$increase_interval",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 42 },
   "targets": [
    {
     "expr": "sum by(status) (increase(client_android_core_login_eaToIafetchDomains_total{status!=\"http2xx\"}[$increase_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Username check - availability/$increase_interval",
   "type": "timeseries",
   "description": "Check if a username is not yet taken by another user.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 50 },
   "targets": [
    { "expression": "$A / ($A + $B) * 100", "type": "math" }
   ]
  },
  {
   "title": "Username check - successes/$increase_interval",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 50 },
   "targets": [
    {
     "expr": "sum by(status) (increase(client_android_core_login_eaToIaUsernameAvailability_total{status=\"http2xx\"}[$increase_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Username check - failures/$increase_interval",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 50 },
   "targets": [
    {
     "expr": "sum by(status) (increase(client_android_core_login_eaToIaUsernameAvailability_total{status!=\"http2xx\"}[$increase_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unlock user - availability/$increase_interval",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 58 },
   "targets": [
    { "expression": "$A / ($A + $B) * 100", "type": "math" }
   ]
  },
  {
   "title": "Unlock user - successes/$increase_interval",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 58 },
   "targets": [
    {
     "expr": "sum by(status) (increase(client_android_core_login_eaToIaUnlockUser_total{status=\"success\"}[$increase_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unlock user - failures/$increase_interval",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 58 },
   "targets": [
    {
     "expr": "sum by(status) (increase(client_android_core_login_eaToIaUnlockUser_total{status!=\"success\"}[$increase_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "User check - availability/$increase_interval",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 66 },
   "targets": [
    { "expression": "$A / ($A + $B) * 100", "type": "math" }
   ]
  },
  {
   "title": "User check - successes/$increase_interval",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 66 },
   "targets": [
    {
     "expr": "sum by(status) (increase(client_android_core_login_eaToIaUserCheck_total{status=\"success\"}[$increase_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "User check - failures/$increase_interval",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 66 },
   "targets": [
    {
     "expr": "sum by(status) (increase(client_android_core_login_eaToIaUserCheck_total{status!=\"success\"}[$increase_interval]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}